config/routes.rb
Rails.application.routes.draw do
  resources :questions

end

app/models/question.rb
class Question < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:text)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>QuestionChallenger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/questions/_form.html.haml
= form_for @question do |f|
  - if @question.errors.any?
    #error_explanation
      %h2= "#{pluralize(@question.errors.count, "error")} prohibited this question from being saved:"
      %ul
        - @question.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :text
    = f.text_area :text
  .actions
    = f.submit 'Save'

app/views/questions/edit.html.haml
%h1 Editing question

= render 'form'

= link_to 'Show', @question
\|
= link_to 'Back', questions_path

app/views/questions/index.html.haml
%h1 Listing questions

%table
  %tr
    %th Text
    %th
    %th
    %th

  - @questions.each do |question|
    %tr
      %td= question.text
      %td= link_to 'Show', question
      %td= link_to 'Edit', edit_question_path(question)
      %td= link_to 'Destroy', question, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Question', new_question_path

app/views/questions/new.html.haml
%h1 New question

= render 'form'

= link_to 'Back', questions_path

app/views/questions/show.html.haml
%p#notice= notice

%p
  %b Text:
  = @question.text

= link_to 'Edit', edit_question_path(@question)
\|
= link_to 'Back', questions_path